// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// GoodBenefit is the predicate function for goodbenefit builders.
type GoodBenefit func(*sql.Selector)
